import 'package:todayq_assignment/utils/enums/analysts_tab.dart';

/// Model for the analyst.
class Analyst {
  /// Constructor for the analyst.
  Analyst({
    required this.id,
    required this.name,
    required this.rewardsGenerated,
    required this.isSubscribedByUser,
    required this.totalSubscribers,
    required this.profilePhoto,
  });

  /// Converts the json to the analyst.
  factory Analyst.fromJson(Map<String, dynamic> json) {
    /// Convert the rewards generated json to a map.
    final rewardsGeneratedJson = json['rewardsGenerated'] as Map<String, num>;
    final rewardsGenerated = <AnalystsTab, num>{};

    /// Convert the rewards generated json to a map of [AnalystsTab] and [num].
    rewardsGeneratedJson.forEach((key, value) {
      rewardsGenerated.addAll({AnalystsTab.fromString(key): value});
    });

    /// Return the analyst.
    return Analyst(
      id: json['id'] as String,
      name: json['name'] as String,
      rewardsGenerated: rewardsGenerated,
      isSubscribedByUser: json['isSubscribedByUser'] as bool,
      totalSubscribers: json['totalSubscribers'] as int,
      profilePhoto: json['profilePhoto'] as String?,
    );
  }

  /// Id of the analyst.
  String id;

  /// Name of the analyst.
  String name;

  /// Rewards generated by the analyst.
  Map<AnalystsTab, num> rewardsGenerated;

  /// Whether the analyst is subscribed by the user.
  bool isSubscribedByUser;

  /// Total subscribers of the analyst.
  int totalSubscribers;

  /// Profile photo of the analyst.
  String? profilePhoto;
}
